#!/usr/bin/env python
"""Auto-generated by quant_agent.measurement. Measures latency, VRAM, and ppl.

Env vars:
  MEASURE_MODEL_PATH   path to quantized model dir (or HF id for fp16 baseline)
  MEASURE_OUTPUT_JSON  where to write the final metrics JSON
  MEASURE_DATASET      dataset name (default: wikitext-2-raw-v1)
  MEASURE_MAX_LENGTH   sliding window length for ppl (default: 2048)
  MEASURE_STRIDE       sliding window stride for ppl (default: 512)
"""
from __future__ import annotations

import gc
import json
import math
import os
import sys
import time

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


def _now_ms() -> float:
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    return time.perf_counter() * 1000.0


def _prefill_decode(model, tokenizer, prompt_len: int, decode_len: int) -> dict:
    text = "Hello, " * (prompt_len * 2)
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=prompt_len)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.inference_mode():
        # warm
        _ = model.generate(**inputs, max_new_tokens=4, do_sample=False, use_cache=True)

        t0 = _now_ms()
        out = model.generate(
            **inputs, max_new_tokens=decode_len, do_sample=False, use_cache=True,
            pad_token_id=tokenizer.eos_token_id or 0,
        )
        t1 = _now_ms()
    elapsed = t1 - t0
    new_tokens = max(int(out.shape[-1] - inputs["input_ids"].shape[-1]), 1)
    return {"elapsed_ms": elapsed, "new_tokens": new_tokens}


def _measure_perplexity(model, tokenizer, dataset_name: str, max_length: int, stride: int) -> float:
    from datasets import load_dataset

    ds = load_dataset(
        "wikitext", dataset_name, split="test"
    )
    text = "\n\n".join(ds["text"])
    encodings = tokenizer(text, return_tensors="pt")
    input_ids = encodings.input_ids.to(model.device)
    seq_len = input_ids.size(1)

    nlls: list[float] = []
    prev_end = 0
    with torch.inference_mode():
        for begin in range(0, seq_len, stride):
            end = min(begin + max_length, seq_len)
            trg_len = end - prev_end
            ids = input_ids[:, begin:end]
            target_ids = ids.clone()
            target_ids[:, :-trg_len] = -100

            out = model(ids, labels=target_ids)
            nll = out.loss.float() * trg_len
            nlls.append(nll.item())

            prev_end = end
            torch.cuda.empty_cache()
            if end == seq_len:
                break

    total_loss = sum(nlls)
    return float(math.exp(total_loss / max(seq_len, 1)))


def main() -> int:
    model_path = os.environ["MEASURE_MODEL_PATH"]
    output_json = os.environ["MEASURE_OUTPUT_JSON"]
    dataset_name = os.environ.get("MEASURE_DATASET", "wikitext-2-raw-v1")
    max_length = int(os.environ.get("MEASURE_MAX_LENGTH", "2048"))
    stride = int(os.environ.get("MEASURE_STRIDE", "512"))

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA GPU required for measurement")

    torch.cuda.reset_peak_memory_stats()
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    model = AutoModelForCausalLM.from_pretrained(
        model_path, trust_remote_code=True, device_map="cuda", torch_dtype="auto",
    )
    model.eval()

    prefill = _prefill_decode(model, tokenizer, prompt_len=2048, decode_len=128)
    decode = _prefill_decode(model, tokenizer, prompt_len=32, decode_len=512)

    vram_gb = torch.cuda.max_memory_allocated() / (1024**3)

    ppl = _measure_perplexity(model, tokenizer, dataset_name, max_length, stride)

    metrics = {
        "prefill_ms": prefill["elapsed_ms"],
        "decode_ms": decode["elapsed_ms"],
        "vram_gb": vram_gb,
        "ppl": ppl,
        "details": {
            "prefill_probe": prefill,
            "decode_probe": decode,
            "model_path": model_path,
            "dataset": dataset_name,
            "max_length": max_length,
            "stride": stride,
        },
    }
    with open(output_json, "w") as f:
        json.dump(metrics, f, indent=2)

    # Sentinel line the parent process greps for in stdout.
    print("MEASUREMENT_RESULT=" + json.dumps(
        {k: metrics[k] for k in ("prefill_ms", "decode_ms", "vram_gb", "ppl")}
    ))

    del model
    gc.collect()
    torch.cuda.empty_cache()
    return 0


if __name__ == "__main__":
    sys.exit(main())
