"""Latency / VRAM / perplexity measurement for quantized (and fp16 baseline) models.

The actual measurement runs as a subprocess in the method's venv (or the synthetic
``_fp16_reference`` venv for the baseline) so it shares the loader semantics of
the quantization step. This module provides:

  - MEASURE_SCRIPT (str): a self-contained measurement script written into the
    job dir. Reads ``MEASURE_MODEL_PATH`` and ``MEASURE_OUTPUT_JSON`` from env.
  - run_measurement(...): writes the script, runs it, parses the JSON it emits.
  - load_metrics(job_dir): convenience reader for jobs/<id>/metrics.json.

The script is intentionally HF-loader-centric: ``AutoModelForCausalLM`` plus
``trust_remote_code=True`` covers the bulk of method outputs (GPTQ via
auto-gptq, AWQ via autoawq, bnb_nf4, fp16 baseline). Method-specific overrides
get emitted by the adapt agent if the README mandates a custom load path.
"""
from __future__ import annotations

import json
import logging
import os
import re
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

from .config import child_env
from .pareto import Metrics

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class MeasurementProbe:
    """Latency probe configuration. Two probes capture both regimes."""
    name: str
    prompt_len: int
    decode_len: int


PROBES: tuple[MeasurementProbe, ...] = (
    MeasurementProbe(name="prefill_heavy", prompt_len=2048, decode_len=128),
    MeasurementProbe(name="decode_heavy", prompt_len=32, decode_len=512),
)


# ---------------------------------------------------------------------------
# Embedded measurement script template
# ---------------------------------------------------------------------------
# Written into the job dir at measure time so it ships alongside the quantize
# script and is reproducible offline. Reads model path + output JSON path from
# env to avoid argparse coupling. All numeric fields are emitted in the final
# JSON line so the parent process can pick them up unambiguously.

MEASURE_SCRIPT = r'''#!/usr/bin/env python
"""Auto-generated by quant_agent.measurement. Measures latency, VRAM, and ppl.

Env vars:
  MEASURE_MODEL_PATH   path to quantized model dir (or HF id for fp16 baseline)
  MEASURE_OUTPUT_JSON  where to write the final metrics JSON
  MEASURE_DATASET      dataset name (default: wikitext-2-raw-v1)
  MEASURE_MAX_LENGTH   sliding window length for ppl (default: 2048)
  MEASURE_STRIDE       sliding window stride for ppl (default: 512)
  MEASURE_TRUST_REMOTE_CODE  "1" to allow executing a model repo's custom code
                             (default: off — only enable for models you trust)
"""
from __future__ import annotations

import gc
import json
import math
import os
import sys
import time

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer


def _now_ms() -> float:
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    return time.perf_counter() * 1000.0


def _prefill_decode(model, tokenizer, prompt_len: int, decode_len: int) -> dict:
    text = "Hello, " * (prompt_len * 2)
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=prompt_len)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.inference_mode():
        # warm
        _ = model.generate(**inputs, max_new_tokens=4, do_sample=False, use_cache=True)

        t0 = _now_ms()
        out = model.generate(
            **inputs, max_new_tokens=decode_len, do_sample=False, use_cache=True,
            pad_token_id=tokenizer.eos_token_id or 0,
        )
        t1 = _now_ms()
    elapsed = t1 - t0
    new_tokens = max(int(out.shape[-1] - inputs["input_ids"].shape[-1]), 1)
    return {"elapsed_ms": elapsed, "new_tokens": new_tokens}


def _measure_perplexity(model, tokenizer, dataset_name: str, max_length: int, stride: int) -> float:
    from datasets import load_dataset

    ds = load_dataset(
        "wikitext", dataset_name, split="test"
    )
    text = "\n\n".join(ds["text"])
    encodings = tokenizer(text, return_tensors="pt")
    input_ids = encodings.input_ids.to(model.device)
    seq_len = input_ids.size(1)

    nlls: list[float] = []
    prev_end = 0
    with torch.inference_mode():
        for begin in range(0, seq_len, stride):
            end = min(begin + max_length, seq_len)
            trg_len = end - prev_end
            ids = input_ids[:, begin:end]
            target_ids = ids.clone()
            target_ids[:, :-trg_len] = -100

            out = model(ids, labels=target_ids)
            nll = out.loss.float() * trg_len
            nlls.append(nll.item())

            prev_end = end
            torch.cuda.empty_cache()
            if end == seq_len:
                break

    total_loss = sum(nlls)
    return float(math.exp(total_loss / max(seq_len, 1)))


def main() -> int:
    model_path = os.environ["MEASURE_MODEL_PATH"]
    output_json = os.environ["MEASURE_OUTPUT_JSON"]
    dataset_name = os.environ.get("MEASURE_DATASET", "wikitext-2-raw-v1")
    max_length = int(os.environ.get("MEASURE_MAX_LENGTH", "2048"))
    stride = int(os.environ.get("MEASURE_STRIDE", "512"))

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA GPU required for measurement")

    # Off by default: loading a hub model with trust_remote_code=True executes that
    # repo's arbitrary Python. Opt in per-run via MEASURE_TRUST_REMOTE_CODE=1.
    trust = os.environ.get("MEASURE_TRUST_REMOTE_CODE") == "1"

    torch.cuda.reset_peak_memory_stats()
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=trust)
    model = AutoModelForCausalLM.from_pretrained(
        model_path, trust_remote_code=trust, device_map="cuda", torch_dtype="auto",
    )
    model.eval()

    prefill = _prefill_decode(model, tokenizer, prompt_len=2048, decode_len=128)
    decode = _prefill_decode(model, tokenizer, prompt_len=32, decode_len=512)

    vram_gb = torch.cuda.max_memory_allocated() / (1024**3)

    ppl = _measure_perplexity(model, tokenizer, dataset_name, max_length, stride)

    metrics = {
        "prefill_ms": prefill["elapsed_ms"],
        "decode_ms": decode["elapsed_ms"],
        "vram_gb": vram_gb,
        "ppl": ppl,
        "details": {
            "prefill_probe": prefill,
            "decode_probe": decode,
            "model_path": model_path,
            "dataset": dataset_name,
            "max_length": max_length,
            "stride": stride,
        },
    }
    with open(output_json, "w") as f:
        json.dump(metrics, f, indent=2)

    # Sentinel line the parent process greps for in stdout.
    print("MEASUREMENT_RESULT=" + json.dumps(
        {k: metrics[k] for k in ("prefill_ms", "decode_ms", "vram_gb", "ppl")}
    ))

    del model
    gc.collect()
    torch.cuda.empty_cache()
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


_RESULT_RE = re.compile(r"MEASUREMENT_RESULT=(\{[^\n}]+\})")


def write_measure_script(job_dir: Path) -> Path:
    """Drop the measurement script into a job directory. Returns the script path."""
    job_dir.mkdir(parents=True, exist_ok=True)
    path = job_dir / "measure.py"
    path.write_text(MEASURE_SCRIPT)
    path.chmod(0o755)
    return path


def run_measurement(
    *,
    job_dir: Path,
    model_path: str,
    venv_python: Path,
    timeout_s: int = 1800,
) -> Metrics:
    """Run the measurement script in the given venv. Returns parsed Metrics.

    Raises:
        RuntimeError: if the script returns non-zero or doesn't emit a metrics JSON.
    """
    script_path = write_measure_script(job_dir)
    output_json = job_dir / "metrics.json"
    log_path = job_dir / "measure.log"

    # Allowlisted env only (see config.child_env): the measurement subprocess loads
    # models from the Hub, so it needs the HF token but none of the cloud secrets.
    # Forward any MEASURE_* overrides the caller set (dataset/window/trust flag).
    measure_overrides = {k: v for k, v in os.environ.items() if k.startswith("MEASURE_")}
    env = child_env(
        {
            **measure_overrides,
            "MEASURE_MODEL_PATH": str(model_path),
            "MEASURE_OUTPUT_JSON": str(output_json),
        }
    )

    with log_path.open("wb") as logf:
        proc = subprocess.run(
            [str(venv_python), str(script_path)],
            stdout=logf,
            stderr=subprocess.STDOUT,
            env=env,
            timeout=timeout_s,
            check=False,
        )

    if proc.returncode != 0 or not output_json.exists():
        tail = log_path.read_text(errors="replace").splitlines()[-30:]
        raise RuntimeError(
            f"Measurement failed (exit={proc.returncode}). Last log lines:\n"
            + "\n".join(tail)
        )

    payload = json.loads(output_json.read_text())
    return Metrics(
        prefill_ms=float(payload["prefill_ms"]),
        decode_ms=float(payload["decode_ms"]),
        vram_gb=float(payload["vram_gb"]),
        ppl=float(payload["ppl"]),
    )


def load_metrics(job_dir: Path) -> Metrics | None:
    """Read jobs/<id>/metrics.json, or None if not present/parseable."""
    p = job_dir / "metrics.json"
    if not p.exists():
        return None
    try:
        d = json.loads(p.read_text())
        return Metrics(
            prefill_ms=float(d["prefill_ms"]),
            decode_ms=float(d["decode_ms"]),
            vram_gb=float(d["vram_gb"]),
            ppl=float(d["ppl"]),
        )
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        log.warning("metrics.json parse failed: %s", e)
        return None


def parse_stdout_metrics(stdout: str) -> Metrics | None:
    """Fallback: pluck MEASUREMENT_RESULT=... line out of captured stdout."""
    m = _RESULT_RE.search(stdout)
    if not m:
        return None
    try:
        d = json.loads(m.group(1))
        return Metrics(
            prefill_ms=float(d["prefill_ms"]),
            decode_ms=float(d["decode_ms"]),
            vram_gb=float(d["vram_gb"]),
            ppl=float(d["ppl"]),
        )
    except (json.JSONDecodeError, KeyError, ValueError):
        return None


def metrics_summary(m: Metrics) -> str:
    """Human-readable one-liner for stdout reports."""
    return (
        f"prefill={m.prefill_ms:.1f}ms  decode={m.decode_ms:.1f}ms  "
        f"vram={m.vram_gb:.2f}GB  ppl={m.ppl:.3f}"
    )


def metrics_to_dict(m: Metrics) -> dict:
    return asdict(m)
