"""Interactive `.env` setup for new EC2 users.

Prompts for required and optional API keys using ``getpass`` (hidden input — the
key never appears on screen and never lands in shell history). Writes the repo's
``.env`` with mode 0600 and refuses to overwrite an existing file unless the
user passes ``--force``.

Optionally validates the Anthropic key with a tiny live call so typos are caught
at setup time instead of at first ``ask`` invocation.
"""
from __future__ import annotations

import getpass
import os
import stat
import sys
from pathlib import Path

import typer

from .config import REPO_ROOT

ENV_PATH = REPO_ROOT / ".env"

_DEFAULT_MODEL = "claude-sonnet-4-6"


def _prompt_secret(label: str, required: bool) -> str | None:
    suffix = "" if required else " (press Enter to skip)"
    while True:
        value = getpass.getpass(f"{label}{suffix}: ").strip()
        if value:
            return value
        if not required:
            return None
        typer.echo("  value required; try again", err=True)


def _prompt_plain(label: str, required: bool) -> str | None:
    suffix = "" if required else " (press Enter to skip)"
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if not required:
            return None
        typer.echo("  value required; try again", err=True)


def _validate_anthropic(key: str) -> tuple[bool, str]:
    """Issue a 1-token live call to confirm the key works. Returns (ok, message)."""
    try:
        from anthropic import Anthropic  # type: ignore
    except ImportError:
        return True, "anthropic SDK not installed; skipping live validation"

    try:
        client = Anthropic(api_key=key)
        client.messages.create(
            model=_DEFAULT_MODEL,
            max_tokens=1,
            messages=[{"role": "user", "content": "hi"}],
        )
        return True, "key accepted by Anthropic API"
    except Exception as e:  # noqa: BLE001 — surface any auth/network issue
        return False, f"{type(e).__name__}: {e}"


def _format_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by `quant-agent setup`. Do not commit.",
        "",
        "# Anthropic Claude API key — required",
        f"ANTHROPIC_API_KEY={values['ANTHROPIC_API_KEY']}",
        "",
        "# Voyage AI — embeddings (voyage-3-lite)",
        f"VOYAGE_API_KEY={values['VOYAGE_API_KEY']}",
        "",
        "# Qdrant Cloud — vector database",
        f"QDRANT_URL={values['QDRANT_URL']}",
        f"QDRANT_API_KEY={values['QDRANT_API_KEY']}",
        "",
        "# Cloudflare R2 — raw file storage (PDFs + repo zips)",
        f"R2_ACCOUNT_ID={values['R2_ACCOUNT_ID']}",
        f"R2_ACCESS_KEY_ID={values['R2_ACCESS_KEY_ID']}",
        f"R2_SECRET_ACCESS_KEY={values['R2_SECRET_ACCESS_KEY']}",
        f"R2_BUCKET_NAME={values['R2_BUCKET_NAME']}",
        "",
        "# Optional: raises GitHub API rate limits for Adapt agent's repo fetches",
    ]
    if values.get("GITHUB_TOKEN"):
        lines.append(f"GITHUB_TOKEN={values['GITHUB_TOKEN']}")
    else:
        lines.append("# GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxxxxxx")
    lines.append("")
    lines.append("# Optional: required for gated HF models (e.g. meta-llama/*)")
    if values.get("HUGGINGFACE_HUB_TOKEN"):
        lines.append(f"HUGGINGFACE_HUB_TOKEN={values['HUGGINGFACE_HUB_TOKEN']}")
    else:
        lines.append("# HUGGINGFACE_HUB_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxxxxx")
    lines.append("")
    lines.append("# Model override (optional)")
    lines.append(f"QUANT_AGENT_MODEL={values.get('QUANT_AGENT_MODEL', _DEFAULT_MODEL)}")
    lines.append("")
    return "\n".join(lines)


def _write_env_file(path: Path, contents: str) -> None:
    path.write_text(contents)
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0600


def run(force: bool = False, validate: bool = True, no_optional: bool = False) -> int:
    """Run interactive setup. Returns process exit code."""
    typer.echo(f"quant-agent setup → {ENV_PATH}")
    typer.echo("This writes a .env file (gitignored, chmod 600) with your API keys.")
    typer.echo("Input is hidden and not stored in shell history.")
    typer.echo("")

    if ENV_PATH.exists() and not force:
        typer.echo(f"Refusing to overwrite existing {ENV_PATH}. Re-run with --force to replace it.", err=True)
        return 1

    if not sys.stdin.isatty():
        typer.echo(
            "Setup must run in an interactive terminal (stdin is not a TTY). "
            "If scripting, write .env yourself or set env vars directly.",
            err=True,
        )
        return 2

    anthropic_key = _prompt_secret("ANTHROPIC_API_KEY", required=True)
    assert anthropic_key  # required path guarantees non-None
    if not anthropic_key.startswith("sk-ant-"):
        typer.echo(
            "  warning: key does not start with 'sk-ant-' — continuing anyway, but double-check it.",
            err=True,
        )

    voyage_key = _prompt_secret("VOYAGE_API_KEY", required=True)
    qdrant_url = _prompt_plain("QDRANT_URL", required=True)
    qdrant_key = _prompt_secret("QDRANT_API_KEY", required=True)
    r2_account_id = _prompt_plain("R2_ACCOUNT_ID", required=True)
    r2_access_key_id = _prompt_secret("R2_ACCESS_KEY_ID", required=True)
    r2_secret_access_key = _prompt_secret("R2_SECRET_ACCESS_KEY", required=True)
    r2_bucket_name = _prompt_plain("R2_BUCKET_NAME", required=True)

    github_token: str | None = None
    hf_token: str | None = None
    if not no_optional:
        github_token = _prompt_secret("GITHUB_TOKEN (optional)", required=False)
        hf_token = _prompt_secret("HUGGINGFACE_HUB_TOKEN (optional)", required=False)

    if validate:
        typer.echo("")
        typer.echo("Validating Anthropic key (1-token live call)...")
        ok, msg = _validate_anthropic(anthropic_key)
        status = "ok" if ok else "FAILED"
        typer.echo(f"  {status}: {msg}")
        if not ok:
            typer.echo("Aborting. Re-run setup or pass --no-validate to skip the check.", err=True)
            return 3

    existing_model = os.environ.get("QUANT_AGENT_MODEL")
    values = {
        "ANTHROPIC_API_KEY": anthropic_key,
        "VOYAGE_API_KEY": voyage_key,
        "QDRANT_URL": qdrant_url,
        "QDRANT_API_KEY": qdrant_key,
        "R2_ACCOUNT_ID": r2_account_id,
        "R2_ACCESS_KEY_ID": r2_access_key_id,
        "R2_SECRET_ACCESS_KEY": r2_secret_access_key,
        "R2_BUCKET_NAME": r2_bucket_name,
        "QUANT_AGENT_MODEL": existing_model or _DEFAULT_MODEL,
    }
    if github_token:
        values["GITHUB_TOKEN"] = github_token
    if hf_token:
        values["HUGGINGFACE_HUB_TOKEN"] = hf_token

    _write_env_file(ENV_PATH, _format_env(values))
    typer.echo("")
    typer.echo(f"Wrote {ENV_PATH} (mode 600). You can now run: quant-agent ask \"...\"")
    return 0
