"""Interactive `.env` setup for new EC2 users.

Prompts for required and optional API keys using ``getpass`` (hidden input — the
key never appears on screen and never lands in shell history). Writes the repo's
``.env`` with mode 0600 and refuses to overwrite an existing file unless the
user passes ``--force``.

Optionally validates the OpenAI key with a model-access check so typos are caught
at setup time instead of at first ``ask`` invocation.
"""
from __future__ import annotations

import getpass
import os
import stat
import sys
from pathlib import Path

import typer

from .config import REPO_ROOT

ENV_PATH = REPO_ROOT / ".env"

_DEFAULT_MODEL = "gpt-5.6-terra"


def _prompt_secret(label: str, required: bool) -> str | None:
    suffix = "" if required else " (press Enter to skip)"
    while True:
        value = getpass.getpass(f"{label}{suffix}: ").strip()
        if value:
            return value
        if not required:
            return None
        typer.echo("  value required; try again", err=True)


def _validate_openai(key: str) -> tuple[bool, str]:
    """Check API authentication and default-model access. Returns (ok, message)."""
    try:
        from openai import OpenAI  # type: ignore
    except ImportError:
        return True, "OpenAI SDK not installed; skipping live validation"

    try:
        client = OpenAI(api_key=key)
        client.models.retrieve(_DEFAULT_MODEL)
        return True, f"key accepted; {_DEFAULT_MODEL} is accessible"
    except Exception as e:  # noqa: BLE001 — surface any auth/network issue
        return False, f"{type(e).__name__}: {e}"


def _format_env(values: dict[str, str]) -> str:
    for key, value in values.items():
        if any(ch in value for ch in ("\n", "\r", "\x00")):
            raise ValueError(f"{key} contains a forbidden newline or NUL byte")
    lines = [
        "# Generated by `quant-agent setup`. Do not commit.",
        "",
        "# OpenAI API key — required",
        f"OPENAI_API_KEY={values['OPENAI_API_KEY']}",
        "",
        "# Optional: raises GitHub API rate limits for Adapt agent's repo fetches",
    ]
    if values.get("GITHUB_TOKEN"):
        lines.append(f"GITHUB_TOKEN={values['GITHUB_TOKEN']}")
    else:
        lines.append("# GITHUB_TOKEN=ghp_xxxxxxxxxxxxxxxxxxxxxxxx")
    lines.append("")
    lines.append("# Optional: required for gated HF models (e.g. meta-llama/*)")
    if values.get("HUGGINGFACE_HUB_TOKEN"):
        lines.append(f"HUGGINGFACE_HUB_TOKEN={values['HUGGINGFACE_HUB_TOKEN']}")
    else:
        lines.append("# HUGGINGFACE_HUB_TOKEN=hf_xxxxxxxxxxxxxxxxxxxxxxxx")
    lines.append("")
    lines.append("# Optional global model override (stage defaults are recommended)")
    if values.get("QUANT_AGENT_MODEL"):
        lines.append(f"QUANT_AGENT_MODEL={values['QUANT_AGENT_MODEL']}")
    else:
        lines.append(f"# QUANT_AGENT_MODEL={_DEFAULT_MODEL}")
    lines.append("")
    return "\n".join(lines)


def _write_env_file(path: Path, contents: str) -> None:
    """Atomically replace ``path``; secret bytes are mode 0600 from first write."""
    if path.is_symlink():
        raise RuntimeError(f"refusing to replace symlink: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    if hasattr(os, "O_NOFOLLOW"):
        flags |= os.O_NOFOLLOW
    fd = os.open(tmp, flags, stat.S_IRUSR | stat.S_IWUSR)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(contents)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
    finally:
        if tmp.exists():
            tmp.unlink()


def run(force: bool = False, validate: bool = True, no_optional: bool = False) -> int:
    """Run interactive setup. Returns process exit code."""
    typer.echo(f"quant-agent setup → {ENV_PATH}")
    typer.echo("This writes a .env file (gitignored, chmod 600) with your API keys.")
    typer.echo("Input is hidden and not stored in shell history.")
    typer.echo("")

    if ENV_PATH.exists() and not force:
        typer.echo(f"Refusing to overwrite existing {ENV_PATH}. Re-run with --force to replace it.", err=True)
        return 1

    if not sys.stdin.isatty():
        typer.echo(
            "Setup must run in an interactive terminal (stdin is not a TTY). "
            "If scripting, write .env yourself or set env vars directly.",
            err=True,
        )
        return 2

    openai_key = _prompt_secret("OPENAI_API_KEY", required=True)
    assert openai_key  # required path guarantees non-None
    if not openai_key.startswith("sk-"):
        typer.echo(
            "  warning: key does not start with 'sk-' — continuing anyway, but double-check it.",
            err=True,
        )

    github_token: str | None = None
    hf_token: str | None = None
    if not no_optional:
        github_token = _prompt_secret("GITHUB_TOKEN (optional)", required=False)
        hf_token = _prompt_secret("HUGGINGFACE_HUB_TOKEN (optional)", required=False)

    if validate:
        typer.echo("")
        typer.echo("Validating OpenAI key and default-model access...")
        ok, msg = _validate_openai(openai_key)
        status = "ok" if ok else "FAILED"
        typer.echo(f"  {status}: {msg}")
        if not ok:
            typer.echo("Aborting. Re-run setup or pass --no-validate to skip the check.", err=True)
            return 3

    existing_model = os.environ.get("QUANT_AGENT_MODEL")
    values = {
        "OPENAI_API_KEY": openai_key,
    }
    if existing_model:
        values["QUANT_AGENT_MODEL"] = existing_model
    if github_token:
        values["GITHUB_TOKEN"] = github_token
    if hf_token:
        values["HUGGINGFACE_HUB_TOKEN"] = hf_token

    _write_env_file(ENV_PATH, _format_env(values))
    typer.echo("")
    typer.echo(f"Wrote {ENV_PATH} (mode 600). You can now run: quant-agent ask \"...\"")
    return 0
